
    <form method="POST" class="register-form" enctype="multipart/form-data">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="sous_categorie">Sous Catagorie</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">
                <select id="id_sous_categorie" name="id_sous_categorie">
                    <?php require('apps/select_souscategorie.php'); ?>
                </select>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="reference">Réference</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                <input type="text" id="reference" name="reference" value="<?= htmlentities( $reference ) ?>">
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="stock">Stock</label>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-9">                    
                <input type="text" id="stock" name="stock" value="<?= htmlentities( $stock ) ?>"> 
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="prix_ht">Prix ht</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                <input type="text" id="prix_ht" name="prix_ht" value="<?= htmlentities( $prix_ht ) ?>"> 
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="tva">Tva</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                <input type="text" id="tva" name="tva" value="<?= htmlentities( $prix_ht ) ?>">
            </div>            
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="description">Déscription</label>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-9">                
                <input type="text" id="description" name="description" value="<?= htmlentities( $description ) ?>">
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="photo">Photo</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                <input type="text" id="photo" name="photo" value="<?= htmlentities( $photo ) ?>">
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="nom">Nom</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                <input type="text" id="nom" name="nom" value="<?= htmlentities( $nom ) ?>">
            </div>
        </div>    

        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="poids">Poids</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                <input type="text" id="poids" name="poids" value="<?= htmlentities( $poids ) ?>"> 
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">
                <label for="actif">Actif</label>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3">                
                Oui <input type="radio" id="actif" name="actif" value="1" checked > 
                Non <input type="radio" name="actif" value="0"
            </div>            
        </div>

         <div class="row">
            <div class="col-sm-12 text-center">   
                <button type="submit" class="btn btn-default" name="action" value="ajout">Ajout</button>   
            </div>
        </div>

    </form>
