<tr>
    <td><a href="?page=admin_produit_modif&id=<?= $produit->getId() ?>">Modif</a></td>
    <td>
        <form method="POST" class="register-form">
            <input type="hidden" name="id" value="<?= htmlentities( $produit->getId() ) ?>">
            <button type="submit" class="button" name="action" value="supp">Supprimer</button>
        </form>
    </td>
    <td><?= htmlentities( $produit->getidSousCategorie() ) ?></td>
    <td><?= htmlentities( $produit->getReference() ) ?></td>
    <td><?= htmlentities( $produit->getStock() ) ?></td>
    <td><?= htmlentities( $produit->getPrixHt() ) ?></td>
    <td><?= htmlentities( $produit->getTva() ) ?></td>
    <td><?= htmlentities( $produit->getDescription() ) ?></td>
    <td><?= htmlentities( $produit->getPhoto() ) ?></td>
    <td><?= htmlentities( $produit->getNom() ) ?></td>
    <td><?= htmlentities( $produit->getPoids() ) ?></td>
    <td><?= htmlentities( $produit->getActif() ) ?></td>
</tr>