<div class="row">
    <div class="col-md-4">
       <p>Note : <?=$avis->getNote()?></p>
    </div>
    <div class="col-md-2">
        <p>Auteur : <?=$avis->getUtilisateur()->getLogin()?></p>
    </div>
</div>

<div class="row">
     <p class="col-md-8">Content : <?=$avis->getContenu()?></p>
</div>

<div>    
    <?=date("m/d/Y H\hi", strtotime($avis->getDate()))?>
    <?php //require('apps/avis.php'); ?>
</div>