<h3>Ajouter une catégorie</h3>

<div class="col-md-6">

    <form method="POST" action="" class="register-form" enctype="multipart/form-data">
        <div class="row">
            <label for="fileToUpload">Choisissez une image pour la catégorie:</label>
            <input type="file" name="fileToUpload" id="fileToUpload">
            <div class="text-center">
                <button class="btn btn-default" type="submit" value="upload" name="action">Uploader l'image
                </button><br>
                <img src="<?=htmlentities($url_image)?>" alt=""><br>
                <?=htmlentities($nom_photo)?>
            </div>
        </div>
    </form>
</div>
<div class="col-md-6">

    <form method="POST" class="register-form" enctype="multipart/form-data">
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <br>
                    <label for="nom">Nom de la catégorie</label><br>
                    <input class="col-xs-12" type="text" id="nom" name="nom" value="<?= htmlentities( $nom ) ?>">
                </div>
            </div>
        </div> 

        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <label for="description">Description</label><br>
                    <input class="col-xs-12" type="text" id="description" name="description" value="<?= htmlentities( $description ) ?>">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 submit text-center">   
                <input type="hidden" name='photo' value='<?= htmlentities( $url_image ) ?>'><br>

                <button type="submit" class="bouton button btn btn-success" name="action" value="ajout">Ajouter</button>   
            </div>
        </div>

    </form>
</div>