<div class="row">
    <div class="col-md-4">
       <p>Note :<?= $avis->getNote() ?></p>
    </div>
</div>
<div class="row">
    <p class="col-md-6">Avis :<?= $avis->getContenu() ?></p>
</div>

<div class="row">
    <div class="col-md-4">    
        <p>Posté le :<?= htmlentities ($date = date("m/d/Y H\hi") ) ?></p>
    </div>

    <div class="col-md-2 submit">   
         <button type="submit" class="bouton button btn btn-success" name="action" value="ajout"><a href="?page=admin_avis_modif">Supprimer</a></button>   
     </div>

</div>
