<div class="row">
    <h1>Gestion des commandes</h1>

    <select id="j-panier-type">
        <option value="0" <?= selected( $type, 0 ) ?>>Voir les commandes en cours</option>
        <option value="1" <?= selected( $type, 1 ) ?>>Voir les commandes payées</option>
        <option value="2" <?= selected( $type, 2 ) ?>>Voir les commandes validées</option>
    </select>
</div>

<div class="row">
    <br>
    <table class="table table-striped table-vertical-align-middle">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Date</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Poids</th>
                <th></th>
            </tr>
        </thead>
        
        <tbody>
            <?php require('apps/admin_commande.php'); ?>
        </tbody>
    </table>

</div>