<div class="row">
    <div><a href="?page=admin_produit_ajout">Nouveau produit</a></div>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Photo</th>
                <th>Nom</th>
                <th>Réference</th>
                <th>Description</th>
                <th>Sous-catégorie</th>
                <th>Poids</th>
                <th>Stock</th>
                <th>Prix HT</th>
                <th>Tva</th>                                       
            </tr>
        </thead>
        
        <tbody>
            <?php require('apps/admin_produit.php'); ?>
        </tbody>
    </table>

</div>