<form method="POST" class="register-form" enctype="multipart/form-data">
    <input type="hidden" id="id" name="id" value="<?= htmlentities( $produit->getId() ) ?>">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="sous_categorie">Sous Catagorie</label>
                <select id="id_sous_categorie" name="id_sous_categorie">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                </select>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="reference">Réference</label>
                <input type="text" id="reference" name="reference" value="<?= htmlentities( $produit->getReference() ) ?>">
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="stock">Stock</label>
                <input type="text" id="stock" name="stock" value="<?= htmlentities( $produit->getStock() ) ?>"> 
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="prix_ht">Prix ht</label>
                <input type="text" id="prix_ht" name="prix_ht" value="<?= htmlentities( $produit->getPrixHt() ) ?>"> 
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="tva">Tva</label>
                <input type="text" id="tva" name="tva" value="<?= htmlentities( $produit->getTva() ) ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="description">Déscription</label>
                <input type="text" id="description" name="description" value="<?= htmlentities( $produit->getDescription() ) ?>">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="photo">Photo</label>
                <input type="text" id="photo" name="photo" value="<?= htmlentities( $produit->getPhoto() ) ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom" value="<?= htmlentities( $produit->getNom() ) ?>">
            </div>
        </div>
    </div>    

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="poids">Poids</label>
                <input type="text" id="poids" name="poids" value="<?= htmlentities( $produit->getPoids() ) ?>"> 
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="actif">Actif</label>
                Oui<input type="radio" id="actif" name="actif" value="1"> 
                Non<input type="radio" name="actif" value="0">                 
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-sm-12 submit">   
            <button type="submit" class="button" name="action" value="modif">Send</button>   
        </div>
    </div>

</form>