<div class="row">
	
    <div class="row">
    	<div><a href="?page=admin_souscategorie_ajout">Nouvelle sous-catégorie</a></div>
	</div>

    <table>
        <tr>
        	<td></td>
        	<td></td>
        	<td>Catégorie</td>
            <td>Photo</td>
            <td>Nom</td> 
            <td>Description</td> 
        </tr>
        <?php require('apps/admin_souscategorie.php'); ?>
    </table>
    
</div>