<div class="row">
    <div><a href="?page=admin_produit_ajout">Nouveau produit</a></div>
    <table>
        <tr>
            <td></td>
            <td></td>
            <td>Sous Catagorie</td>
            <td>Réference</td> 
            <td>Stock</td>
            <td>Prix ht</td>
            <td>Tva</td>
            <td>Déscription</td> 
            <td>Photo</td>
            <td>Nom</td> 
            <td>Poids</td>
            <td>Actif</td>                                      
        </tr>
        <?php require('apps/admin_produit.php'); ?>
    </table>
</div>