<tr>

    <td><?= htmlentities( $date = date("m/d/Y H\hi") ) ?></td>
    <td><?= htmlentities( $avis->getProduit()->getNom() ) ?></td>
    <td><?= htmlentities( $avis->getUtilisateur()->getLogin() ) ?></td>
    <td><?= htmlentities( $avis->getContenu() ) ?></td>
    <td><?= htmlentities( $avis->getStar() ) ?></td>

    <td>
        <a class="bouton button btn btn-success" href="?page=admin_avis_modif&id=<?= $avis->getId() ?>">Modifier</a>
    </td>
    <td>
        <form method="POST" class="register-form">
            <input type="hidden" name="id" value="<?= htmlentities( $avis->getId() ) ?>">
             <button type="submit" class="bouton button btn btn-success" name="action" value="supp">Supprimer</button> 
        </form> 
    </td>
</tr>