<tr>
    <td><a href="?page=admin_produit_modif&id=<?= $produit->getId() ?>">Modif</a></td>
    <td>
        <form method="POST" class="register-form">
            <input type="hidden" name="id" value="<?= htmlentities( $produit->getId() ) ?>">
            <button type="submit" class="button" name="action" value="supp">Supprimer</button>
        </form>
    </td>
    <td><?= $produit->getidSousCategorie() ?></td>
    <td><?= $produit->getReference() ?></td>
    <td><?= $produit->getStock() ?></td>
    <td><?= $produit->getPrixHt() ?></td>
    <td><?= $produit->getTva() ?></td>
    <td><?= $produit->getDescription() ?></td>
    <td><?= $produit->getPhoto() ?></td>
    <td><?= $produit->getNom() ?></td>
    <td><?= $produit->getPoids() ?></td>
    <td><?= $produit->getActif() ?></td>
</tr>