<tr>
    <td><img src="<?= $produit->getPhoto() ?>" alt="<?= $produit->getNom() ?>"/></td>
    <td><?= htmlentities( $produit->getNom() ) ?></td>
    <td><?= htmlentities( $produit->getReference() ) ?></td>
    <td><?= htmlentities( $produit->getDescription() ) ?></td>
    <td><?= htmlentities( $produit->getSousCategorie()->getNom() ) ?></td>
    <td><?= htmlentities( $produit->getPoids() ) ?></td>
    <td><?= htmlentities( $produit->getStock() ) ?></td>
    <td><?= htmlentities( $produit->getPrixHt() ) ?></td>
    <td><?= htmlentities( $produit->getTva() ) ?></td>

    <td><a class="bouton button btn btn-success" href="?page=admin_produit_modif&id=<?= $produit->getId() ?>">Modifier</a></td>
    <td>
        <form method="POST" class="register-form">
            <input type="hidden" name="id" value="<?= htmlentities( $produit->getId() ) ?>">
            <button type="submit" class="bouton button btn btn-success" name="action" value="supp">Supprimer</button>
        </form>
    </td>
</tr>