<div class="row">
    <div><a href="?page=admin_avis_ajout">Nouvel avis</a>
    </div>
        <div class="col-md-2">
           <p>Note</p>
        </div>
        <div class="col-md-2">
            <p>Titre avis</p>
        </div>
         <p>Contenu</p>
        <div class="col-md-2">
            <p>Avis</p>
        </div>
        <div class="col-md-2">    
            <?= htmlentities ($date = date("m/d/Y H\hi") ) ?>
        </div>
</div>