<div class="row">
    <h2>Gestion des produits</h2>
    <div><a class="bouton button btn btn-success" href="?page=admin_produit_ajout">Nouveau produit</a></div>
    
    <div class="table-responsive">
        <table class="table table-striped table-vertical-align-middle">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Nom</th>
                    <th>Référence</th>
                    <th>Description</th>
                    <th>Sous-catégorie</th>
                    <th>Poids</th>
                    <th>Stock</th>
                    <th>Prix HT</th>
                    <th>Tva</th>
                    <th></th> 
                    <th></th> 
                </tr>
            </thead>
            
            <tbody>
                <?php require('apps/admin_produit.php'); ?>
            </tbody>
        </table>
    </div>

</div>