<div class="row">
	<div class="col-md-6">
		<div class="row">
		     <p class="col-md-8"><?=$avis->getContenu()?></p>
		</div>
	</div>
	<div class="col-md-6">
		<div class="col-md-4">
		   <p>Note : <?=$avis->getStar()?></p>
		</div>

		<div class="col-md-4">
		    <p>Auteur : <?=$avis->getUtilisateur()->getLogin()?></p>
		</div>

		<div class="col-md-4">    
		    <p>Date : <?=date("m/d/Y H\hi", strtotime($avis->getDate()))?></p>
		</div>
	</div>
</div>	