<form method="POST" class="register-form" enctype="multipart/form-data">
	<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">


	<div class="row">
		<div class="col-md-2"> 
			<label for="pseudo">Date :</label><br> 
	        <?= htmlentities ($date = date("m/d/Y H\hi") ) ?><br> <br> 
	    </div>

		<div class="col-md-7">
			<label for="pseudo">Votre avis :</label>
				<textarea class="form-control" id="contenu" name="contenu" value="<?= htmlentities ( $contenu ) ?>"></textarea><br> 
		</div>

	    <div class="col-md-2"> 
	        <label for="note">Notez ce produit!</label>
	        <br>

	    	<select name="note" class="notes fa">
				<option value="5" selected class="fa note-star"></option>	
		        <option value="4>" class="fa note-star"></option>	
		        <option value="3" class="fa note-star"></option>	
		        <option value="2" class="fa note-star"></option>	
		        <option value="1" class="fa note-star"></option>
	    	</select>

	    	<br>
	    	<br>
	    </div>

		<div class="col-md-2 submit">   
            <button type="submit" class="bouton button btn btn-success" name="action" value="admin_avis_ajout"><a href="?page=avis">Publier mon avis</a></button>   
        </div>
    </div>
</form>


    

    