<tr>
    <td><?= htmlentities( $avis->getIdUtilisateur() ) ?></td>
    <td><?= htmlentities( $avis->getIdProduit() ) ?></td>
    <td><?= htmlentities( $avis->getContenu()->getNom() ) ?></td>
    <td><?= htmlentities( $avis->getNote() ) ?></td>

    <td><a href="?page=avis_modif&id=<?= $avis->getId() ?>">Modif</a></td>

    <td>
    	<form method="POST" class="register-form">
			<input type="hidden" name="id_avis" value="<?<?= htmlentities( $avis->getId() ) ?>">
			<button type="submit" class="bouton button btn btn-success" name="action" value="supp">Supprimer</button>   
		</form>
	</td>
</tr>



    
    
