<form method="POST" class="register-form" enctype="multipart/form-data">
	<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">


	<div class="row">
		<div class="col-md-2">    
	        <?= htmlentities ($date = date("m/d/Y H\hi") ) ?>
	    </div>

		<div class="col-md-7">
			<label for="pseudo">Votre avis</label>
				<textarea class="form-control" rows="3" id="contenu" name="contenu" value="<?= htmlentities ( $contenu ) ?>">
				</textarea>
		</div>

	    <div class="col-md-2"> 
	        <label for="note">Note de 1 à 5</label>
	            <input type="text" id="note" name="note" value="<?= htmlentities ( $note ) ?>">
	    </div>

		<div class="col-md-2 submit">   
            <button type="submit" class="bouton button btn btn-success" name="action" value="admin_avis_ajout"><a href="?page=avis">Publier</a></button>   
        </div>
    </div>
</form>


    

    