<p>
    <a href="?page=categories">Catégorie</a> <?= htmlentities( $produit->getSouscategorie()->getCategorie()->getNom() ) ?> >
    <a href="?page=souscategories&id_categorie=<?= htmlentities( $produit->getSouscategorie()->getCategorie()->getId() ) ?>">Sous Catégorie</a> <?= htmlentities( $produit->getSouscategorie()->getNom() ) ?> >
     <a href="?page=produits&id_sous_categorie=<?= htmlentities( $produit->getSouscategorie()->getId() ) ?>">Produit</a> <?= htmlentities( $produit->getNom() ) ?> >    
</p>

<div class="row">
    <div class="col-sm-12">
        <div class="cadre_produit panel panel-default">
            <div class="panel-body">
                <img class="pull-right" src="<?= $produit->getPhoto() ?>" alt="<?= $produit->getNom() ?>">
                <h3><?= htmlentities( $produit->getNom() ) ?></h3>
                <p>Sous catégorie : <?= htmlentities( $produit->getSousCategorie()->getNom() ) ?></p>
                <p>Référence : <?= htmlentities( $produit->getReference() ) ?></p>
                <p>En stock : <?= htmlentities( $produit->getStock() ) ?></p>
                <p>Prix HT : <?= htmlentities( $produit->getPrixHt() ) ?> €</p>
                <p>Prix TTC : <?= htmlentities( $produit->getPrixTtc() ) ?> € dont <?= htmlentities( $produit->getTvaValue() ) ?> € de tva</p>
                <p>Description : <?= htmlentities( $produit->getDescription() ) ?></p>
                <p>Poids : <?= htmlentities( $produit->getPoidsKg() ) ?> Kg</p> 
                <?php require('apps/detail_produit_button.php'); ?>
            </div>
        </div>
        <div class="cadre_produit panel panel-default">
            <div class="panel-body">
                <h3>Votre avis sur le produit : <?= htmlentities( $produit->getNom() ) ?></h3>
                <?php require('apps/avis_ajout.php'); ?>
                <h3>Des clients ont donné leur avis sur : <?= htmlentities( $produit->getNom() ) ?></h3>
                <?php require('apps/avisliste.php'); ?>
            </div>
        </div>
    </div>
</div>