<div class="modal fade bs-example-modal-sm in" tabindex="-1" role="dialog" style="display: block; padding-right: 15px;">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button> 
				<h4 class="modal-title">Erreur</h4>
			</div>
			<div class="modal-body">
				<p><?=$error?></p>
			</div>
		</div>
	</div>
</div>
<script>
$('.modal').modal('show');
</script>