<footer class="footer">
	<div class="container">
		<p>Guitare - Basse - Batterie - Clavier - Piano - Saxophone - Trompette - Clarinette - Flûte - Cajon - Accessoire - Accordeur - Câble - Pupitre - Partition - Effet - Classique - Électrique - Acoustique - Etc.</p>
		<p class="text-muted">Musikdream : l'avant-dernier numéro de la vente en ligne d'instruments de musique. © 2016 Musikdream. 3W Academy TP E-commerce by Alice-Éric-Olivier-Patrick.</p>
	</div>
</footer>