<div class="header">
    <nav class="navbar navbar-inverse">
        <div class="musik_dream col-xs-12">
            <p><a href="?page=articles">Musikdream</a></p>
        </div>
        <a href="?page=articles">
            <img class ="banniere" src= "public/images/banniere1c.jpeg" alt="banniere"/>
        </a>
        <div class="row">                        
            <div class="col-sm-12">
                <ul class="nav navbar-nav">
                    <li><a href="index.php">Accueil</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <form action="recherche" method="post">
                        <div class="input-group col-md-12">
                            <input class="form-control input-sm" type="text" placeholder="Rechercher sur le site...">
                            <span class="input-group-btn">
                                <button class="bouton-recherche btn btn-info btn-sm" type="button">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="index.php?page=register">Créer mon compte</a></li>
                    <li><a href="index.php?page=login">Connexion</a></li>
                    <li><a class="voir_panier" href="?page=panier" title="Voir mon panier" alt="Voir mon panier"><img class ="panier" src= "public/images/panier.png"/></a></li>
                    <li class="quantite_panier"><p></p></li>
                </ul>
            </div>
        </div>
    </nav>    
</div>