<div class="header">
    <nav class="navbar navbar-inverse">
        <div class="row">                        
            <div class="col-lg-12 col-md-8">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.php">Home</a></li>
                    <li><a href="index.php?page=logout">Logout</a></li>
                    <li>Admin
                        <ul>
                            <li><a href="index.php?page=admin_categories">Catégories</a></li>
                            <li><a href="index.php?page=admin_produits">Produits</a></li>
                            <li><a href="index.php?page=admin_avislit">Avis</a></li>
                        </ul>
                    </li>
                </ul>
                <p>Bonjour <?= htmlentities( $_SESSION['login']) ?></p>
                <a href="?page=profil">Modifier mon profil</a>

            </div>      
        </div>
    </nav>   
</div>