<div class="header">
    <nav class="navbar navbar-inverse">
        <img class ="banniere" src= "public/images/banniere1c.jpeg"/>
        <h1 class="musik_dream">Musikdream</h1>
        <div class="row">                        
            <div class="col-sm-12">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.php">Catégories</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li><a href="index.php?page=register">Créer mon compte</a></li>
                    <li><a href="index.php?page=login">Se connecter</a></li>
                    <a href="?page=panier" title="panier" alt="panier"><img class ="panier" src= "public/images/panierb.png"/></a>
                </ul>
            </div>
        </div>
    </nav>    
</div>