<div class="header">
    <nav class="navbar navbar-inverse">
        <div class="musik_dream col-xs-12">
            <p><a href="?page=articles">Musikdream</a></p>
        </div>
        <a href="?page=articles">
            <img class ="banniere" src= "public/images/banniere1c.jpeg" alt="banniere"/>
        </a>
        <div class="row">                        
            <div class="col-sm-12">
                <ul class="nav navbar-nav">
                    <li><a href="index.php">Accueil</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="index.php?page=register">Créer mon compte</a></li>
                    <li><a href="index.php?page=login">Connexion</a></li>
                    <li><a class="voir_panier" href="?page=panier" title="Voir mon panier" alt="Voir mon panier"><img class ="panier" src= "public/images/panier.png"/></a></li>
                    <li class="quantite_panier"><p></p></li>
                </ul>
            </div>
        </div>
    </nav>    
</div>
<form action="index.php" method="get">
    <div class="form-group">
        <input type="hidden" value="recherches" name="page">
        <div class="input-group input-group-md icon-addon addon-md">
            <input type="text" placeholder="Rechercher sur le site..." name="s" id="js-search" class="form-control">
                <i class="icon icon-search"></i>
            <span class="input-group-btn">
                <button type="submit" class="bouton-recherche btn btn-inverse" name="action" value="recherche">
                    <i class="glyphicon glyphicon-search"></i>
                    Rechercher
                </button>
            </span>
        </div>
    </div>
</form>
<div class="row" id="js-result">

</div>