<div class="header">
    <nav class="navbar navbar-inverse">
        <div class="musik_dream col-xs-12">
            <p><a href="?page=articles">Musikdream</a></p>
        </div>
        <a href="?page=articles">
            <img class ="banniere" src= "public/images/banniere1c.jpeg"/>
        </a>
        <div class="row">                        
            <div class="col-sm-12">
                <ul class="nav navbar-nav">
                    <li><a href="index.php">Accueil</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="bonjour"><a>Bonjour <?= htmlentities( $_SESSION['login']) ?></a></li>
                    <li><a href="?page=profil">Mon profil</a></li>
                    <li><a href="index.php?page=logout">Déconnexion</a></li>
                    <li><a class="voir_panier" href="?page=panier" title="Voir mon panier" alt="Voir mon panier"><img class ="panier" src= "public/images/panier.png"/></a></li>
                    <li class="quantite_panier"><?php require('apps/header_display_quantite.php') ?></li>
                </ul>
            </div>    
        </div>     
    </nav>    
</div>
<form action="recherche" method="post">
    <div class="form-group">
        <div class="input-group input-group-md icon-addon addon-md">
            <input type="text" placeholder="Rechercher sur le site..." name="" id="schbox" class="form-control">
                <i class="icon icon-search"></i>
            <span class="input-group-btn">
                <button type="submit" class="bouton-recherche btn btn-inverse">
                    <i class="glyphicon glyphicon-search"></i>
                    Rechercher
                </button>
            </span>
        </div>
    </div>
</form>