<form class="form-inline" method="POST" enctype="multipart/form-data">
    <div class="form-group col-md-6">
        <label class="sr-only col-md-12" for="login">Login : </label>
        <input class="col-xs-12" type="text" id="login" name="login" placeholder="Login*" value="<?= htmlentities( $login ) ?>"> 
    </div>
    <div class="form-group col-md-6">
        <label class="sr-only col-md-12" for="mot_passe">Mot de passe</label>
        <input class="col-xs-12" type="password" id="mot_passe" name="mot_passe" placeholder="Mot de passe*">
    </div>
    <div class="row">
        <div class="form-group col-md-12 col-sm-12 col-xs-12 text-center">
            <button type="submit" class="bouton button btn btn-success" name="action" value="login">Me connecter</button>
        </div>
    </div>
</form>