<form method="POST" class="register-form" enctype="multipart/form-data">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <label for="login">Login</label>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6">            
            <input type="text" id="login" name="login" value="<?= htmlentities( $login ) ?>"> 
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <label for="mot_passe">Mot de passe</label>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6">              
            <input type="password" id="mot_passe" name="mot_passe">
        </div>
    </div>

     <div class="row">
        <div class="col-sm-12 text-center">   
            <button type="submit" class="button" name="action" value="login">Envoyer</button>   
        </div>
    </div>    
</form>