<div class="">
	
 	<h3>Mon panier</h3>
	<div class="col-sm-8">
		<?php require('apps/panier_produit.php'); ?>
	</div>

	<div class="col-sm-4">
		<div class="cadre_produit panel panel-info">
			<div class="panel-heading">
				Etat de votre panier
			</div>
			<!-- <div class="panel-body cadre_produit"> -->
			<div class="panel-body">
					<?=htmlentities( $panier->getQuantite() ) ?> produits dans votre panier<br>
					<strong>Prix total TTC : <?=number_format($prix_total, 2, '.', '')?> €</strong><br>
					Poids total : <?=number_format($poids_total,2,'.','') ?> kg<br>
					<!-- <em>(Status : <?=htmlentities( $panier->getStatus() ) ?>)</em><br> -->
					<!-- <em>(Date : <?=htmlentities( $panier->getDate() ) ?>)</em><br> -->
			</div>
		</div>

		<form action="" method="post">
			<input type='hidden' name="page" value='panier'>
			<button type="submit" name="action" class="btn btn-success pull-right" value="acheter">Passer à la caisse</button>
		</form>

		<form action="">
			<button type="submit" name="page" class="btn btn-primary" value="home">Poursuivre mes achats</button>
		</form>
	</div>
</div>

