<!-- <div class="container"> -->

<div class="panel panel-default">
	<div class="panel-body">

		<img class="pull-right" src="<?=htmlentities( $produit->getPhoto() ) ?>">
		<h3><?=htmlentities( $produit->getNom() ) ?></h3>
		<div>
			Référence : <?=htmlentities( $produit->getReference() ) ?>
		</div>
		<div>
			description
			<p>
				<?=htmlentities( $produit->getdescription() ) ?>
			</p>
			poids : <?=$poids ?> kg
		</div>
		<div>
			En stock : <?=htmlentities( $produit->getStock() ) ?> pièces
		</div>
		<div>
			<h5>
				<strong>
					Prix TTC : <?=$prix?> €<br>
					dont TVA : <?=number_format($tva, 2, '.', '')?> €
				</strong>
			<h5>
		</div>

		
		<div class="pull-left">
			nombre de produits :&nbsp
		</div>

		<form action="">
			<select name="quantite_produit" class="pull-left">
				<option value=1 <?=$option_selected[$quantite][0] ?>>1</option>
				<option value=2 <?=$option_selected[$quantite][1] ?>>2</option>
				<option value=3 <?=$option_selected[$quantite][2] ?>>3</option>
				<option value=4 <?=$option_selected[$quantite][3] ?>>4</option>
				<option value=5 <?=$option_selected[$quantite][4] ?>>5</option>
				<option value=6 <?=$option_selected[$quantite][5] ?>>6</option>
				<option value=7 <?=$option_selected[$quantite][6] ?>>7</option>
				<option value=8 <?=$option_selected[$quantite][7] ?>>8</option>
				<option value=9 <?=$option_selected[$quantite][8] ?>>9</option>




			</select>

			<input type='hidden' name="page" value='panier'>
			<button type="submit" name="action" class="btn btn-warning btn-xs pull-left"value="panier_modif">
				Modifier mon panier
			</button>

			<button type="submit" name="action" class="btn btn-warning btn-xs pull-right"value="retirer">
				Retirer ce produit du panier
			</button>
		</form>
	</div>

</div>