<div class="container">
	<div class="row">
		<h2>mon panier</h2>
	</div>
	<div class="col-sm-8">
		ici les produits du panier
		<?php require('apps/panier_produit.php'); ?>
	</div>

	<div class="col-sm-4">
		<div>
			Date : 25/04/2016
		</div>
		<div>
			Status : En traitement
		</div>
		<div>
			Quantité : 5 produits dans votre panier
		</div>
		<div>
			Prix : 124.52€
		</div>
		<div>
			Poids : 20kg
		</div>
	</div>
</div>

