<div class="col-sm-12">
    <div class="cadre_produit panel panel-default">
        <div class="titre_cadre_produit panel-heading">
            <?= htmlentities( $produit->getSousCategorie()->getNom() ) ?>
        </div>
        <div class="cadre_produit panel-body text-center">
            <a href="?page=detail_produit&id_produit=<?= $produit->getId() ?>">
                <img src="<?= $produit->getPhoto() ?>" alt="<?= $produit->getNom() ?>">
            </a>
        </div>
    </div>
</div>