<form method="POST" class="register-form" enctype="multipart/form-data">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3">
            <label for="nom">Nom</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">            
            <input type="text" id="nom" name="nom" value="<?= htmlentities( $nom ) ?>">
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3"> 
            <label for="prenom">Prénom</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">            
            <input type="text" id="prenom" name="prenom" value="<?= htmlentities( $prenom ) ?>">
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3"> 
            <label for="email">Email</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">            
            <input type="email" id="email" name="email" value="<?= htmlentities( $email ) ?>"> 
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">
            <label for="date_naissance">Date de naissance</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">            
            <input type="date" id="date_naissance" name="date_naissance" value="<?= htmlentities( $date_naissance ) ?>">
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3">
            <label for="mot_passe">Mot de passe</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">                  
            <input type="password" id="mot_passe" name="mot_passe" value="<?= htmlentities( $mot_passe ) ?>">
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">
            <label for="confirme_mot_passe">Confirmez le mot de passe</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">                  
            <input type="password" id="confirme_mot_passe" name="confirme_mot_passe" value="<?= htmlentities( $confirme_mot_passe ) ?>">
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3">
            <label for="telephone">Téléphone</label>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">                  
            <input type="text" id="telephone" name="telephone" value="<?= htmlentities( $telephone ) ?>">
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">
            <label for="sexe">Sexe</label><br>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">                  
            <input type="radio" name="sexe" value="0" selected> Femme<br>
            <input type="radio" name="sexe" value="1"> Homme<br>
        </div>
    </div>    

    <div class="row">
        <div class="col-sm-12 col-md-3">
            <label for="login">Login</label>
        </div>
        <div class="col-sm-12 col-md-9">
            <input type="text" id="login" name="login" value="<?= htmlentities( $login ) ?>"> 
        </div>
    </div>

     <div class="row">
        <div class="col-sm-12 text-center">   
            <button type="submit" class="button" name="action" value="register">Envoyer</button>   
        </div>
    </div>

</form>