<form method="POST" class="register-form" enctype="multipart/form-data">
    <div class ="col-md-6 col-sm-12 col-xs-12">
        <div class="row">
            <div class="col-md-12">
                <label class="sr-only col-md-12" for="nom">Nom</label>
            </div>
            <div class="col-md-12">            
                <input class="col-xs-12" type="text" id="nom" name="nom" placeholder="Nom*" value="<?= htmlentities( $nom ) ?>">
            </div>
            <div class="col-md-12"> 
                <label class="sr-only col-md-12" for="prenom">Prénom</label>
            </div>
            <div class="col-md-12">            
                <input class="col-xs-12" type="text" id="prenom" name="prenom" placeholder="Prénom*" value="<?= htmlentities( $prenom ) ?>">
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12"> 
                <label class="sr-only col-md-12" for="email">Email</label>
            </div>
            <div class="col-md-12">
                <input class="col-xs-12" type="email" id="email" name="email" placeholder="Email*" value="<?= htmlentities( $email ) ?>"> 
            </div>
            <div class="col-md-12">
                <label class="sr-only col-md-12" for="date_naissance">Date de naissance</label>
            </div>
            <div class="col-md-12">            
                <input class="col-xs-12" type="date" id="date_naissance" name="date_naissance" placeholder="Date de naissance* jj/mm/aaaa" value="<?= htmlentities( $date_naissance ) ?>">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label class="sr-only col-md-12" for="login">Login</label>
            </div>
            <div class="col-md-12">
                <input class="col-xs-12" type="text" id="login" name="login" placeholder="Login*" value="<?= htmlentities( $login ) ?>"> 
            </div>
        </div>
    </div>

    <div class ="col-md-6 col-sm-12 col-xs-12">
        <div class="row">
            <div class="col-md-12">
                <label class="sr-only col-md-12" for="mot_passe">Mot de passe</label>
            </div>
            <div class="col-md-12">                  
                <input class="col-xs-12" type="password" id="mot_passe" name="mot_passe" placeholder="Mot de passe*" value="<?= htmlentities( $mot_passe ) ?>">
            </div>
            <div class="col-md-12">
                <label class="sr-only col-md-12" for="confirme_mot_passe">Confirmez le mot de passe</label>
            </div>
            <div class="col-md-12">                  
                <input class="col-xs-12" type="password" id="confirme_mot_passe" name="confirme_mot_passe" placeholder="Confirmez votre mot de passe*" value="<?= htmlentities( $confirme_mot_passe ) ?>">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <label class="sr-only col-md-12" for="telephone">Téléphone</label>
            </div>
            <div class="col-md-12">
                <input class="col-xs-12" type="text" id="telephone" name="telephone" placeholder="Téléphone*" value="<?= htmlentities( $telephone ) ?>">
            </div>
            <div class="col-md-12">
                <label for="sexe">Sexe* :</label>
            </div>
            <div class="col-md-12">
                <div class="col-xs-12">
                    <input type="radio" name="sexe" value="0" selected> Femme
                </div>

                <div class="col-xs-12">
                    <input type="radio" name="sexe" value="1"> Homme
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12 col-sm-12 col-xs-12 text-center">
            <button type="submit" class="bouton button btn btn-success" name="action" value="register">M'enregistrer</button>
        </div>
    </div>
</form>
