<!DOCTYPE html>
<html lang="fr">
    <head>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="<?= CSS_PATH ?>bootstrap.min.css" />
        <link rel="stylesheet/less" type="text/css" href="<?= CSS_PATH ?>style.less" />
        <script src="<?= JS_PATH ?>jquery-2.2.3.min.js"></script>
        <script src="<?= JS_PATH ?>bootstrap.min.js"></script>
        <script src="<?= JS_PATH ?>main.js"></script>
        <script src="<?= JS_PATH ?>less.min.js"></script>
        <title></title>
    </head>
    </head>
    <body>
        <div class="container">

            <?php require("apps/header.php"); ?>

            <div class="main">   
            <?php 
                require("apps/content.php"); 
                require("apps/footer.php");
            ?>         
            </div>

        </div>
    </body>
</html>